### ISSUE TITLE
Compile problem.

### ISSUE THREAD

**Issue by Malganys** [WopsS/PawnPlus#14]
Hey, I have a little problem, the program says that the archive was compiled but they doesn't.

![img1](https://cloud.githubusercontent.com/assets/10390992/5606632/ac2a8afe-9416-11e4-9566-a7245a5ee448.png)
![img2](https://cloud.githubusercontent.com/assets/10390992/5606633/ac2e8a28-9416-11e4-9d65-987f67a965e2.png)

**Comment by WopsS** [comment]
Hi,

Please try running the program with Administrator rights ***(Run as Administrator)***.
