### ISSUE TITLE
little error with highlight

### ISSUE THREAD

**Issue by Malganys** [WopsS/PawnPlus#16]
Hi, I found this error:

![img1](https://cloud.githubusercontent.com/assets/10390992/5634526/3940de76-95bf-11e4-881d-b1c81b62ff55.png)
![img2](https://cloud.githubusercontent.com/assets/10390992/5634527/394c4702-95bf-11e4-99a8-53a9ddafca35.png)

**Comment by WopsS** [comment]
Thank you for reporting it. 

This will be fixed in new version 0.4.9. 
(This is fixed in c01e77f)
