### ISSUE TITLE
Problems with file assoc when open it.

### ISSUE THREAD

**Issue by Malganys** [WopsS/PawnPlus#18]
![img3](https://cloud.githubusercontent.com/assets/10390992/6006568/4ed9cf20-aaf2-11e4-8348-de6138b2089d.png)

Console output: ************** Texto de la excepción **************
System.InvalidOperationException: The DockPanel has already been initialized.
   en WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, Stream stream, DeserializeDockContent deserializeContent, Boolean closeStream)
   en WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, String fileName, DeserializeDockContent deserializeContent)
   en PawnPlus.Main.Main_Load(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PawnPlus
    Versión del ensamblado: 0.4.9.0
    Versión Win32: 0.4.9.0
    Código base: file:///C:/Program%20Files%20(x86)/PawnPlus/PawnPlus.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing

Hope that will be fixed in next version.

**Comment by WopsS** [comment]
Can you tell me steps for that?

**Comment by Malganys** [comment]
Create a .pwn file and assoc it with PawnPlus.exe and try to open it.

**Comment by WopsS** [comment]
Fixed in 16b71e6bbf90df936c56cffc4348bf773236c115.
