### ISSUE TITLE
Multilanguage option.

### ISSUE THREAD

**Issue by WopsS** [WopsS/PawnPlus#5]
Add an option for multilanguage, description of  SA-MP methods will be translated by Google Translate using **API**.

**Comment by Malganys** [comment]
This will be nice, but I prefer that users made the translates because Google Translator is a shit.

**Comment by WopsS** [comment]
Do you want to translate description for 400+ native functions from SA:MP?

**Comment by Malganys** [comment]
I can.

**Comment by JohnyMac** [comment]
@Malganys WOW.

@WopsS Why don't you just get the translations from the wiki itself.

**Comment by WopsS** [comment]
@JohnyMac I do that, but in english.
